### ISSUE TITLE
Relay URL Validation

### ISSUE THREAD

**Issue by average-gary** [erskingardner/whitenoise#8]
When entering a relay URL, validation should ensure I enter the correct prefix (ws:// or wss://), as well as other syntax items.

A step beyond this validation would be pinging a relay as it is added to confirm it exists and is reachable. It should not prohibit use of a non-reachable relay but a warning should be provided to the user.

**Comment by erskingardner** [comment]
Is this as part of the onboarding flow?

**Comment by erskingardner** [comment]
I've added some basic validation for those relay inputs with simple errors in 0c8c084211b113b086d4739c7a02bb53476b63d4. I'm not going to do the step of checking relay existence at this point but I'll keep a note of it for the future.
