### ISSUE TITLE
need more build instructions

### ISSUE THREAD

**Issue by rabble** [erskingardner/whitenoise#9]
Seems like there's a problem with the setup or access of the datastore... i know this is a work in progress but i'm seeing updateAccountsStore failing to invoke.

**Comment by erskingardner** [comment]
Are you seeing this on the console straight away when starting up the app? Can you also tell me more about what system you're using?

**Comment by erskingardner** [comment]
@rabble I added a bunch more details for building in release mode to the readme. Let me know if you're still having trouble.
